### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Kurtiii** [google-pay/wallet-samples#1]
`class POST response: { "error": { "code": 403, "message": "Permission denied.", "errors": [ { "message": "Permission denied.", "domain": "walletobjects", "reason": "permissionDenied" } ] } } object GET or POST response: { "error": { "code": 403, "message": "Permission denied.", "errors": [ { "message": "Permission denied.", "domain": "walletobjects", "reason": "permissionDenied" } ] } } https://pay.google.com/gp/v/save/eyJ0eXAi...`

Does someone know why I get this error?

**Comment by Kurtiii** [comment]
I forgot to add permissions in the Google Wallet API-Console

**Comment by suoko** [comment]
@Kurtiii I have the same error, can you pls give us step by step instructions to fix permissions on wallet api console ?

**Comment by Kurtiii** [comment]
> @Kurtiii I have the same error, can you pls give us step by step instructions to fix permissions on wallet api console ?

Yes. I'll write to you in a few minutes

**Comment by Kurtiii** [comment]
@suoko Do you have your @iam.gserviceaccount.com Email Adress and is your Wallet API request approved?

**Comment by Kurtiii** [comment]
@suoko okay go to your Pay Business Console (https://pay.google.com/business/console/) and then to "users". Click on "invite a user" and enter the @iam.gserviceaccount.com Email Address there (dont forget to select the access level -> you have to choose "developer"). Now click on invite and you are done. Wait a couple of minutes and it should work :)

**Comment by Kurtiii** [comment]
@suoko did it worked?

**Comment by Kurtiii** [comment]
> Heyy, I have the same issue ! I am also getting Permission denied as an error, although I have gone to "invite a user" and then entered the @iam.gserviceaccount.com Email Address (access level -> you have to choose "admin"), is there anything else that might causing this ?

Try to set it to "developer". Otherwise please send your full error message :)

**Comment by Eleftheria-99** [comment]
Thank you I will try it !

**Comment by Kurtiii** [comment]
@Eleftheria-99 was this helpful?

**Comment by Eleftheria-99** [comment]
@Kurtiii I changed the access level for @iam.gserviceaccount.com to "developer", but I am still getting the following error 

`insertClassResult GaxiosError: Permission denied.
  at Gaxios._request (/usr/src/app/node_modules/gaxios/build/src/gaxios.js:130:23)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async JWT.requestAsync (/usr/src/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
  at async Object.exports.insertEventTicketClass (/usr/src/app/src/controllers/gPay/googleApiForGPay.js:79:20)
  at async exports.generateGpayPass (/usr/src/app/src/controllers/gPay/generateGpayPass.js:89:25)
  at async exports.getUserInfo (/usr/src/app/src/controllers/getUserInfo.js:438:25) {
  response: {
  config: {
    url: 'https://walletobjects.googleapis.com/walletobjects/v1/eventTicketClass',
    method: 'POST',
    data: [Object],
    headers: [Object],
    paramsSerializer: [Function: paramsSerializer],
    body: '{"eventName":{"translatedValues":[{"kind":"walletobjects#eventTicketClass","language":"en-US","value":"RESIDENT CARD"}],"defaultValue":{"kind":"walletobjects#eventTicketClass","language":"el-GR","value":"ΚΑΡΤΑ ΔΗΜΟΤΗ"}},"eventId":"kLNIQ02OHDjhbu3xkNp8USxl6nOLSqv5HOLanEtK72I+9Gs9tdAZzFekY4G8DQ==","logo":{"sourceUri":{"uri":"https://www.crowdpolicy.com/wp-content/uploads/2020/01/kit-cp-icon-black.png"},"contentDescription":{"translatedValues":[{"kind":"walletobjects#eventTicketClass","language":"en-US","value":"Cityon Pass Logo"}],"defaultValue":{"kind":"walletobjects#eventTicketClass","language":"el-GR","value":"Cityon Pass Logo"}}},"id":"3388000000022115000.EVENTTICKET_OBJECT_2f61beda-1538-49aa-ae0c-028a1b4b9e45","issuerName":"Crowdpolicy","reviewStatus":"UNDER_REVIEW","review":{"comments":"This is a comment!"},"countryCode":"en-US","enableSmartTap":false,"hexBackgroundColor":"#03A5B9","localizedIssuerName":{"translatedValues":[{"language":"en-US","value":"Crowdpolicy"}],"defaultValue":{"language":"el-GR","value":"Crowdpolicy"}},"multipleDevicesAndHoldersAllowedStatus":"ONE_USER_ALL_DEVICES"}',
    validateStatus: [Function: validateStatus],
    responseType: 'json'
  },
  data: { error: [Object] },
  headers: {
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    'cache-control': 'private',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Tue, 12 Jul 2022 08:42:04 GMT',
    server: 'ESF',
    'transfer-encoding': 'chunked',
    vary: 'Origin, X-Origin, Referer',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '0'
  },
  status: 403,
  statusText: 'Forbidden',
  request: {
    responseURL: 'https://walletobjects.googleapis.com/walletobjects/v1/eventTicketClass'
  }
   },  config: {
  url: 'https://walletobjects.googleapis.com/walletobjects/v1/eventTicketClass',
  method: 'POST',
  data: {
    eventName: [Object],
    eventId: 'kLNIQ02OHDjhbu3xkNp8USxl6nOLSqv5HOLanEtK72I+9Gs9tdAZzFekY4G8DQ==',
    logo: [Object],
    id: '3388000000022115000.EVENTTICKET_OBJECT_2f61beda-1538-49aa-ae0c-028a1b4b9e45',
    issuerName: 'Crowdpolicy',
    reviewStatus: 'UNDER_REVIEW',
    review: [Object],
    countryCode: 'en-US',
    enableSmartTap: false,
    hexBackgroundColor: '#03A5B9',
    localizedIssuerName: [Object],
    multipleDevicesAndHoldersAllowedStatus: 'ONE_USER_ALL_DEVICES'
  },
  headers: {
    Authorization: 'Bearer ya29.c.b0AXv0zTOL-NiFyPDljA7picx4b3cLn4Eyb3HcWO2ORj-NuSxZsCqcUhtKvRDw3e70nR39MVx-FA6kbhaQjErTiHQb09aan5m3qKfHHS_tCWb6O7P5Sdu_HQ97mSGrcrk88hKtSwNr5aJhZmjquVB65-hRnrWbhIzt12MbPDekuTNsvuPd7SVJODa4hEIRUW0hEEZEP4Kn-Pmr-Wzh5H7UZC0Q58WyCKs........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
    'User-Agent': 'google-api-nodejs-client/8.1.0',
    'x-goog-api-client': 'gl-node/14.19.1 auth/8.1.0',
    'Content-Type': 'application/json',
    Accept: 'application/json'
  },
  paramsSerializer: [Function: paramsSerializer],
  body: '{"eventName":{"translatedValues":[{"kind":"walletobjects#eventTicketClass","language":"en-US","value":"RESIDENT CARD"}],"defaultValue":{"kind":"walletobjects#eventTicketClass","language":"el-GR","value":"ΚΑΡΤΑ ΔΗΜΟΤΗ"}},"eventId":"kLNIQ02OHDjhbu3xkNp8USxl6nOLSqv5HOLanEtK72I+9Gs9tdAZzFekY4G8DQ==","logo":{"sourceUri":{"uri":"https://www.crowdpolicy.com/wp-content/uploads/2020/01/kit-cp-icon-black.png"},"contentDescription":{"translatedValues":[{"kind":"walletobjects#eventTicketClass","language":"en-US","value":"Cityon Pass Logo"}],"defaultValue":{"kind":"walletobjects#eventTicketClass","language":"el-GR","value":"Cityon Pass Logo"}}},"id":"3388000000022115000.EVENTTICKET_OBJECT_2f61beda-1538-49aa-ae0c-028a1b4b9e45","issuerName":"Crowdpolicy","reviewStatus":"UNDER_REVIEW","review":{"comments":"This is a comment!"},"countryCode":"en-US","enableSmartTap":false,"hexBackgroundColor":"#03A5B9","localizedIssuerName":{"translatedValues":[{"language":"en-US","value":"Crowdpolicy"}],"defaultValue":{"language":"el-GR","value":"Crowdpolicy"}},"multipleDevicesAndHoldersAllowedStatus":"ONE_USER_ALL_DEVICES"}',
  validateStatus: [Function: validateStatus],
  responseType: 'json'
 },
     code: 403,
     errors: [
  {
    message: 'Permission denied.',
    domain: 'walletobjects',
    reason: 'permissionDenied'
  }
   ]
 }
`
