### ISSUE TITLE
修改会员卡信息

### ISSUE THREAD

**Issue by wangershuai** [google-pay/wallet-samples#10]
请问Node.js中创建了会员卡之后, 如何修改会员卡中的积分以及有效期

**Comment by bekah-murphy** [comment]
Hello, to modify the card after creation we recommend using the [update API](https://developers.google.com/wallet/generic/rest/v1/genericobject/update) to change attributes on the card. Please reach out to our [support team](https://developers.google.com/wallet/retail/loyalty-cards/resources/faq#how-do-i-contact-technical-support-support) with additional questions.
