### ISSUE TITLE
on java payload is always invalid not sure what's going on 

### ISSUE THREAD

**Issue by ag039st** [google-pay/wallet-samples#22]
Exception in thread "main" com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://walletobjects.googleapis.com/walletobjects/v1/genericClass/
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"\": Root element must be a message.",
    "errors": [
      {
        "message": "Invalid JSON payload received. Unknown name \"\": Root element must be a message.",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"\": Root element must be a message."
          }
        ]
      }
    ]
  }
}

	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at DemoGeneric.main(DemoGeneric.java:111)

**Comment by ncalteen** [comment]
PR submitted and pending review

**Comment by ag039st** [comment]
thanks it worked
