### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ReelLion** [google-pay/wallet-samples#29]
Hello!

Thank you for reaching out. I didn't see any text/comments in the issue you created. If there is something you'd like help with, please reopen this issue and add in any comments or questions. I'd be happy to help out :)

_Originally posted by @ncalteen in https://github.com/google-pay/wallet-samples/issues/27#issuecomment-1238138981_

**Comment by ncalteen** [comment]
Hello again, apologies, it looks like this is just a copy of my comment on the previous issue you opened. If you'd like to ask a question, please add a new comment to this issue and I will reply as soon as I can.

I will leave this issue open for a few days :)
