### ISSUE TITLE
Can you help i just need a new google wallet loyalty pass

### ISSUE THREAD

**Issue by CsehRafin** [google-pay/wallet-samples#38]
Hey, 
Please give me the instructions to use and successfully get a google wallet loyalty pass

**Comment by ncalteen** [comment]
Hello,

If you follow the README file for the programming language you'd like to use, that should get you started. If you run into any errors, please reopen this issue with the error message and we can help out!

* [Java](https://github.com/google-pay/wallet-samples/blob/main/java/README.md)
* [.NET](https://github.com/google-pay/wallet-samples/blob/main/dotnet/README.md)
* [Node.js](https://github.com/google-pay/wallet-samples/blob/main/nodejs/README.md)
* [PHP](https://github.com/google-pay/wallet-samples/blob/main/php/README.md)
* [Python](https://github.com/google-pay/wallet-samples/blob/main/python/README.md)
