### ISSUE TITLE
محفوظة فعالي قابلي في تركيا اضنه خدمات أرباح الإنترنت youtube.com/@ahmetcemmalfirebase loginError Code: 50058
Request Id: 

### ISSUE THREAD

**Issue by hmdjml4764** [google-pay/wallet-samples#40]
https://github.com/google-pay/wallet-samples/issues/39

**Comment by ncalteen** [comment]
Hello,

If you are experiencing an issue with the Google Wallet samples or have a question about how to use them, please create a new issue and be sure to include any relevant comments.

Thank you!
