### ISSUE TITLE
How to integrate with xamarin app

### ISSUE THREAD

**Issue by 007vel** [google-pay/wallet-samples#41]
I need to add a passes in google wallet in xamarin application. how to use .net library for xamarin app?

thanks in advacne

**Comment by ncalteen** [comment]
Hello!

The .NET examples use the [C# Google Wallet API client library](https://developers.google.com/wallet/generic/resources/libraries#c). When you download the library, you will see a few files in the archive:

* `Google.Apis.Walletobjects.v1.1.10.0.00.nuspec`
* `Google.Apis.Walletobjects.v1.cs`
* `Google.Apis.Walletobjects.v1.csproj`
* `packages.config`

The library is implemented in `Google.Apis.Walletobjects.v1.cs`. This can be included as a code file in your Xamarin app (you can safely ignore/remove the others if you already have a project with your main app code).

You will need to edit the main project file of your Xamarin app (`.csproj`) and add a reference to the `.cs` file from the client library. An example can be found [here](https://github.com/ncalteen/wallet-samples/blob/main/dotnet/wallet-rest-samples.csproj).

```xml
<CodeFiles Include="lib/Google.Apis.Walletobjects.v1.cs" />
```

After that, make sure you have set the path to your service account key in the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. More info about setting this up can be found [here](https://developers.google.com/wallet/generic/web/prerequisites).

I hope this helps! If you're running into specific errors, please reply back with the error message and any related code snippets.

**Comment by ncalteen** [comment]
Hello,

It's been a while since we heard from you regarding this issue. If you still need any assistance, please reopen this issue with additional information and I'll help as quickly as I can!
