### ISSUE TITLE
I need help with making it work it's not working for me 

### ISSUE THREAD

**Issue by CsehRafin** [google-pay/wallet-samples#43]
please help me make a loyalty card

**Comment by ncalteen** [comment]
Hello!

I'd be happy to help out. When you try to make a Loyalty card, are you getting a specific error message? If you could reply back with the error and the code that is causing it, I can help debug the issue.

**Comment by ncalteen** [comment]
Hello,

It's been a while since we heard from you regarding this issue. If you still need any assistance, please reopen this issue with additional information and I'll help as quickly as I can!
