### ISSUE TITLE
Invalid resource ID

### ISSUE THREAD

**Issue by victorfernandesraton** [google-pay/wallet-samples#60]
When i put something as a classid for creating a ticket example i recive this

```js
 code: 400,
  errors: [
    {
      message: 'Invalid resource ID: invitio.invitioticket',
      domain: 'walletobjects',
      reason: 'invalidResource'
    }
  ]
```

**Comment by stephenmcd** [comment]
One of the following criteria likely hasn't been met:

- you didn't create the class yet
- the class ID is in invalid format, it should be "google-issuer-id.your-chosen-class-id" ("invitio" would be an invalid issuer ID)

Please check these are met and re-open this issue if you still get the same error.
