### ISSUE TITLE
Java Implementation

### ISSUE THREAD

**Issue by ddstallworth** [google-pay/wallet-samples#63]
Having trouble implementing a pass, it generates a very basic pass even though I've populated both class and object values. Here is what I'm getting: 
![image](https://user-images.githubusercontent.com/82616215/222068802-24f133c3-f7c2-44e5-a3df-4d0c793d8d78.png)

But here is what I'm attempting to generate:
![image](https://user-images.githubusercontent.com/82616215/222067756-b63d796f-0e21-443b-96ac-cd47121dbda1.png)

Here is how I configured my code to build both the class and object. My question is despite me populating all the fields in the template object. Why is none of the info generated?

`public String CreateJWTNewObjects(String issuerId, String classSuffix, String objectSuffix) {
    GenericClass newClass = new GenericClass()
            .setId(String.format("%s.%s", issuerId, classSuffix))
            .setClassTemplateInfo(
                    new ClassTemplateInfo()
                            .setCardTemplateOverride(
                                    new CardTemplateOverride()
                                            .setCardRowTemplateInfos(Arrays.asList(
                                              new CardRowTemplateInfo().setThreeItems(
                                                      new CardRowThreeItems()
                                                              .setStartItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['group_#']")))))
                                                              .setMiddleItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['suffix']")))))
                                                              .setEndItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['family_id']")))))),
                                              new CardRowTemplateInfo().setThreeItems(
                                                      new CardRowThreeItems()
                                                              .setStartItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['pkg']")))))
                                                              .setMiddleItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['rxbin']")))))
                                                              .setEndItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['rxpcn']")))))),
                                              new CardRowTemplateInfo().setOneItem(
                                                      new CardRowOneItem()
                                                              .setItem(new TemplateItem().setFirstValue(new FieldSelector().setFields(Arrays.asList( new FieldReference().setFieldPath("object.textModulesData['rxgrp']")))))
                                            )))));

    // See link below for more information on required properties
    // https://developers.google.com/wallet/generic/rest/v1/genericobject
    GenericObject newObject =
            new GenericObject()
                    .setId(String.format("%s.%s", issuerId, objectSuffix))
                    .setClassId(String.format("%s.%s", issuerId, classSuffix))
                    .setState("ACTIVE")
                    .setTextModulesData(
                            Arrays.asList(
                                    new TextModuleData()
                                            .setHeader("GROUP #")
                                            .setBody("V09999")
                                            .setId("group_#"),
                                    new TextModuleData()
                                            .setHeader("SUFFIX")
                                            .setBody("00")
                                            .setId("suffix"),
                                    new TextModuleData()
                                            .setHeader("FAMILY ID")
                                            .setBody("00101212")
                                            .setId("family_id"),
                                    new TextModuleData()
                                            .setHeader("PKG")
                                            .setBody("SLV2")
                                            .setId("pkg"),
                                    new TextModuleData()
                                            .setHeader("RXBIN")
                                            .setBody("001122")
                                            .setId("rxbin"),
                                    new TextModuleData()
                                            .setHeader("RXPCN")
                                            .setBody("0A8")
                                            .setId("rxpcn"),
                                    new TextModuleData()
                                            .setHeader("RXGRP")
                                            .setBody("RX4")
                                            .setId("rxgrp")
                            ))
                    .setBarcode(new Barcode().setType("QR_CODE").setValue("QR code value"))
                    .setCardTitle(
                            new LocalizedString()
                                    .setDefaultValue(
                                            new TranslatedString().setLanguage("en-US").setValue("random txt")))
                    .setHeader(
                            new LocalizedString()
                                    .setDefaultValue(
                                            new TranslatedString().setLanguage("en-US").setValue("Jackie Jill")))
                    .setHexBackgroundColor("#296044")
                    .setLogo(
                            new Image()
                                    .setSourceUri(
                                            new ImageUri()
                                                    .setUri("https://storage.cloud.google.com/viva-logos/google_wallet_logo.png"))
                                    .setContentDescription(
                                            new LocalizedString()
                                                    .setDefaultValue(
                                                            new TranslatedString()
                                                                    .setLanguage("en-US")
                                                                    .setValue("random txt"))));

    // Create the JWT as a HashMap object
    HashMap<String, Object> claims = new HashMap<String, Object>();
    claims.put("iss", ((ServiceAccountCredentials) credentials).getClientEmail());
    claims.put("aud", "google");
    claims.put("origins", new ArrayList<>());
    claims.put("typ", "savetowallet");

    // Create the Google Wallet payload and add to the JWT
    HashMap<String, Object> payload = new HashMap<String, Object>();
    payload.put("genericClasses", Arrays.asList(newClass));
    payload.put("genericObjects", Arrays.asList(newObject));
    claims.put("payload", payload);

    // The service account credentials are used to sign the JWT
    Algorithm algorithm =
            Algorithm.RSA256(
                    null, (RSAPrivateKey) ((ServiceAccountCredentials) credentials).getPrivateKey());
    String token = JWT.create().withPayload(claims).sign(algorithm);

    System.out.println("Add to Google Wallet link");
    System.out.println(String.format("https://pay.google.com/gp/v/save/%s", token));

    return String.format("https://pay.google.com/gp/v/save/%s", token);
  }`

**Comment by stephenmcd** [comment]
I think it would be a lot more useful to look at the underling JSON of newObject and newClass variables - not sure what the methods are for getting those (might even just be toString, but the IDE should help), but if you can provide the JSON you may even be able to compare it directly to the documentation to see what's going wrong.

**Comment by ddstallworth** [comment]
> I think it would be a lot more useful to look at the underling JSON of newObject and newClass variables - not sure what the methods are for getting those (might even just be toString, but the IDE should help), but if you can provide the JSON you may even be able to compare it directly to the documentation to see what's going wrong.

I used the Generic Wallet Pass Editor at [https://developers.google.com/wallet/generic/resources/pass-editor](url) to help creating the JSON. Now I'm trying to implement this JSON in Java.

Here is the class JSON:

`{
  "id": "ISSUER_ID.CLASS_ID",
  "classTemplateInfo": {
    "cardTemplateOverride": {
      "cardRowTemplateInfos": [
        {
          "threeItems": {
            "startItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['group_#']"
                  }
                ]
              }
            },
            "middleItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['suffix']"
                  }
                ]
              }
            },
            "endItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['family_id']"
                  }
                ]
              }
            }
          }
        },
        {
          "threeItems": {
            "startItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['pkg']"
                  }
                ]
              }
            },
            "middleItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['rxbin']"
                  }
                ]
              }
            },
            "endItem": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['rxpcn']"
                  }
                ]
              }
            }
          }
        },
        {
          "oneItem": {
            "item": {
              "firstValue": {
                "fields": [
                  {
                    "fieldPath": "object.textModulesData['rxgrp']"
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}`

Here is the object JSON:
`{
  "id": "ISSUER_ID.OBJECT_ID",
  "classId": "ISSUER_ID.GENERIC_CLASS_ID",
  "logo": {
    "sourceUri": {
      "uri": "https://storage.cloud.google.com/viva-logos/google_wallet_logo.png"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en",
        "value": ""
      }
    }
  },
  "cardTitle": {
    "defaultValue": {
      "language": "en",
      "value": "Viva Health"
    }
  },
  "header": {
    "defaultValue": {
      "language": "en",
      "value": "Jackie Jill"
    }
  },
  "textModulesData": [
    {
      "id": "group_#",
      "header": "GROUP #",
      "body": "V09999"
    },
    {
      "id": "suffix",
      "header": "Suffix",
      "body": "00"
    },
    {
      "id": "family_id",
      "header": "FAMILY ID",
      "body": "00101212"
    },
    {
      "id": "pkg",
      "header": "PKG",
      "body": "SLV2"
    },
    {
      "id": "rxbin",
      "header": "RXBIN",
      "body": "001122"
    },
    {
      "id": "rxpcn",
      "header": "RXPCN",
      "body": "0A8"
    },
    {
      "id": "rxgrp",
      "header": "RXGRP",
      "body": "RX4VIVA"
    }
  ],
  "barcode": {
    "type": "BARCODE_TYPE_UNSPECIFIED",
    "value": "BARCODE_VALUE",
    "alternateText": "Effective 11-09-2020"
  },
  "hexBackgroundColor": "#296044"
}`

**Comment by stephenmcd** [comment]
Is that the JSON being created by the Java objects? From what you wrote it sounds like it isn't. I meant it would be more useful for debugging to look at that.

**Comment by ddstallworth** [comment]
So here is the JSON of the Java objects using ObjectMapper to turn them into a JSON string:

Wallet Class: 
`{
	"classTemplateInfo": {
		"cardTemplateOverride": {
			"cardRowTemplateInfos": [{
				"threeItems": {
					"endItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['family_id']"
							}]
						}
					},
					"middleItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['suffix']"
							}]
						}
					},
					"startItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['group_#']"
							}]
						}
					}
				}
			}, {
				"threeItems": {
					"endItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['rxpcn']"
							}]
						}
					},
					"middleItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['rxbin']"
							}]
						}
					},
					"startItem": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['pkg']"
							}]
						}
					}
				}
			}, {
				"oneItem": {
					"item": {
						"firstValue": {
							"fields": [{
								"fieldPath": "object.textModulesData['rxgrp']"
							}]
						}
					}
				}
			}]
		}
	},
	"id": "3388000000022189673.2c445707-edeb-40bf-a488-4e32aecd861b"
}`

Wallet Object:
`{
	"barcode": {
		"type": "QR_CODE",
		"value": "QR code value"
	},
	"cardTitle": {
		"defaultValue": {
			"language": "en-US",
			"value": "random txt"
		}
	},
	"classId": "3388000000022189673.aa1618af-3594-4535-946b-42e1e502ea9a",
	"header": {
		"defaultValue": {
			"language": "en-US",
			"value": "Jackie Jill"
		}
	},
	"hexBackgroundColor": "#296044",
	"id": "3388000000022189673.eec183a5-6a94-4da7-bc98-e5867f601cd6",
	"logo": {
		"contentDescription": {
			"defaultValue": {
				"language": "en-US",
				"value": "random txt"
			}
		},
		"sourceUri": {
			"uri": "https://storage.cloud.google.com/viva-logos/google_wallet_logo.png"
		}
	},
	"state": "ACTIVE",
	"textModulesData": [{
		"body": "V09999",
		"header": "GROUP #",
		"id": "group_#"
	}, {
		"body": "00",
		"header": "SUFFIX",
		"id": "suffix"
	}, {
		"body": "00101212",
		"header": "FAMILY ID",
		"id": "family_id"
	}, {
		"body": "SLV2",
		"header": "PKG",
		"id": "pkg"
	}, {
		"body": "001122",
		"header": "RXBIN",
		"id": "rxbin"
	}, {
		"body": "0A8",
		"header": "RXPCN",
		"id": "rxpcn"
	}, {
		"body": "RX4",
		"header": "RXGRP",
		"id": "rxgrp"
	}]
}`

**Comment by stephenmcd** [comment]
I think you're only looking at the initial screen which previews the pass - it should have an "view pass" link underneath it, which when clicked will show the full pass. Using the JSON you provided, I see the full pass you expected when I click on "view pass". If there is something else going wrong, please re-open this issue.
