### ISSUE TITLE
No information on how to get the newly created pass back to the client

### ISSUE THREAD

**Issue by InfamyStudio** [google-pay/wallet-samples#65]
How do I now use this python implementation to now get the pass based on its unique ID?

**Comment by aaronball** [comment]
If you have created a class and an object the function create_jwt_existing_objects in each of the samples will create an "Add to Google Wallet" link.

**Comment by InfamyStudio** [comment]
I managed to work that out, thank you. The generic docs on website are really not clear and are not correct in many instances. For example the endpoints to get an object just return 404, whereas this JWT method works well. Is there anyway to track how many passes/objects have been issued per class and get the IDs for each?

**Comment by bekah-murphy** [comment]
@InfamyStudio Can you provide more detail on what is not correct in the documentation? We would like to file a bug internally to have it fixed.

If you could also provide any other details on the error you are seeing when calling the GET API (https://developers.google.com/wallet/generic/rest/v1/genericobject/get) that would be great. Please check you are using the correct syntax for `resourceID` when calling GET which is `{issuerID}.{objectID}` and you are using the correct OAuth scope `https://www.googleapis.com/auth/wallet_object.issuer`.

Additionally, currently the APIs do not support getting all objects per class.

**Comment by bekah-murphy** [comment]
Closing this issue for now due to inactivity.
