### ISSUE TITLE
In python some pip errors

### ISSUE THREAD

**Issue by T0F1Q2007** [google-pay/wallet-samples#67]
_**First:**_
from google.auth.transport.requests import AuthorizedSession
ModuleNotFoundError: No module named 'google'
_**Second:**_ ### Solved
'pipenv' is not recognized as an internal or external command,
operable program or batch file
I solved the second one by searching the internet and downloading it.

**Comment by stephenmcd** [comment]
The error indicates the sample code can't find the required dependencies, which would indicate you either didn't install the dependencies into the virtual environment, or haven't activated the virtual environment.

Please ensure you follow the README from start to finish, which will allow you to avoid these errors.

**Comment by Nooknook88** [comment]
Please send me a more detailed description of what I need to do.
