### ISSUE TITLE
How to add "Add to Google Wallet" button in email

### ISSUE THREAD

**Issue by michalsznajder** [google-pay/wallet-samples#8]
I am in the business of selling event tickets. When ticket is sold we send confirmation email to our customer. In email we have button called "Add to Apple Wallet". This button links to our backed and when pressed download special file (a "bundle" in Apple's language) that can be added to Apple Wallet.

I would like to add similar functionality for Google Wallet. I looked at docs as well as samples in this repo and I am confused. In order to create "object" I always have to call [Google Wallet REST APIs](https://developers.google.com/wallet/). Only then I can create a link in form of `$"https://pay.google.com/gp/v/save/{token}"` that is can be embedded into email.  This means that I have to "register" our tickets in your system regardless if someone is using Google Wallet or not.

Is there a way to create "object" on my own, on our server?

**Comment by ContactlessWiki** [comment]
@michalsznajder You would have better luck getting a response by going to the Support tab in the Google Pay and Wallet Console.

**Comment by bekah-murphy** [comment]
Hello, we recommend that you create an internal save link the email and create the JWT after the user shows that they want to Add to Google Wallet by clicking this link. After the JWT is created, at that time you can redirect the user to the Google Add to Wallet flow. Please reach out to our support team (https://developers.google.com/wallet/retail/loyalty-cards/resources/faq#how-do-i-contact-technical-support-support) with any further questions. Thanks!
